// <auto-generated />
using System;
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20230609163426_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AvailabilityStatus")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("IntakeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            AvailabilityStatus = true,
                            Description = "Curious and cuddly Scottish Fold. Gets along well with other cats and dogs.",
                            IntakeDate = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Winnie",
                            Type = "Cat",
                            Weight = 8
                        },
                        new
                        {
                            AnimalId = 2,
                            AvailabilityStatus = true,
                            Description = "Curious and cuddly Scottish Fold. Gets along well with other cats and dogs.",
                            IntakeDate = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tucker",
                            Type = "Dog",
                            Weight = 8
                        },
                        new
                        {
                            AnimalId = 3,
                            AvailabilityStatus = true,
                            Description = "Fluffy and independent Maine Coon. Prefers a calm environment without other pets.",
                            IntakeDate = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mittens",
                            Type = "Cat",
                            Weight = 6
                        },
                        new
                        {
                            AnimalId = 4,
                            AvailabilityStatus = true,
                            Description = "Energetic and loyal Labrador Retriever. Great with kids and loves to play fetch.",
                            IntakeDate = new DateTime(2023, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Buddy",
                            Type = "Dog",
                            Weight = 12
                        },
                        new
                        {
                            AnimalId = 5,
                            AvailabilityStatus = true,
                            Description = "Playful and affectionate Siamese. Enjoys being the center of attention.",
                            IntakeDate = new DateTime(2023, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Luna",
                            Type = "Cat",
                            Weight = 7
                        },
                        new
                        {
                            AnimalId = 6,
                            AvailabilityStatus = false,
                            Description = "Gentle and well-behaved Boxer. Gets along with other dogs and children.",
                            IntakeDate = new DateTime(2023, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Max",
                            Type = "Dog",
                            Weight = 10
                        },
                        new
                        {
                            AnimalId = 7,
                            AvailabilityStatus = false,
                            Description = "Curious and playful Bengal. Requires mental stimulation and active playtime.",
                            IntakeDate = new DateTime(2023, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Simba",
                            Type = "Cat",
                            Weight = 9
                        },
                        new
                        {
                            AnimalId = 8,
                            AvailabilityStatus = true,
                            Description = "Cheerful and obedient Beagle. Enjoys long walks and exploring new scents.",
                            IntakeDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bailey",
                            Type = "Dog",
                            Weight = 6
                        },
                        new
                        {
                            AnimalId = 9,
                            AvailabilityStatus = true,
                            Description = "Laid-back and affectionate Ragdoll. Loves being held and cuddled.",
                            IntakeDate = new DateTime(2023, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Oscar",
                            Type = "Cat",
                            Weight = 5
                        },
                        new
                        {
                            AnimalId = 10,
                            AvailabilityStatus = true,
                            Description = "Strong and protective Rottweiler. Needs an experienced owner and plenty of exercise.",
                            IntakeDate = new DateTime(2023, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rocky",
                            Type = "Dog",
                            Weight = 14
                        },
                        new
                        {
                            AnimalId = 11,
                            AvailabilityStatus = true,
                            Description = "Sweet and friendly Tabby. Gets along well with other cats and loves to explore.",
                            IntakeDate = new DateTime(2023, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Coco",
                            Type = "Cat",
                            Weight = 7
                        },
                        new
                        {
                            AnimalId = 12,
                            AvailabilityStatus = true,
                            Description = "Active and playful Jack Russell Terrier. Requires mental stimulation and regular exercise.",
                            IntakeDate = new DateTime(2023, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Charlie",
                            Type = "Dog",
                            Weight = 9
                        },
                        new
                        {
                            AnimalId = 13,
                            AvailabilityStatus = true,
                            Description = "Independent and graceful Persian. Prefers a calm and quiet environment.",
                            IntakeDate = new DateTime(2023, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lily",
                            Type = "Cat",
                            Weight = 6
                        },
                        new
                        {
                            AnimalId = 14,
                            AvailabilityStatus = true,
                            Description = "Friendly and outgoing Border Collie. Excels at agility training and learning new tricks.",
                            IntakeDate = new DateTime(2023, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cooper",
                            Type = "Dog",
                            Weight = 11
                        },
                        new
                        {
                            AnimalId = 15,
                            AvailabilityStatus = true,
                            Description = "Playful and mischievous Sphynx. Enjoys interactive toys and warm laps.",
                            IntakeDate = new DateTime(2023, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Milo",
                            Type = "Cat",
                            Weight = 8
                        },
                        new
                        {
                            AnimalId = 16,
                            AvailabilityStatus = false,
                            Description = "Gentle and affectionate Cavalier King Charles Spaniel. Great with families and seniors.",
                            IntakeDate = new DateTime(2023, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Daisy",
                            Type = "Dog",
                            Weight = 7
                        },
                        new
                        {
                            AnimalId = 17,
                            AvailabilityStatus = true,
                            Description = "Curious and playful Abyssinian. Loves interactive toys and climbing.",
                            IntakeDate = new DateTime(2023, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nala",
                            Type = "Cat",
                            Weight = 7
                        },
                        new
                        {
                            AnimalId = 18,
                            AvailabilityStatus = true,
                            Description = "Loyal and protective German Shepherd. Requires an experienced owner and consistent training.",
                            IntakeDate = new DateTime(2023, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Milo",
                            Type = "Dog",
                            Weight = 13
                        },
                        new
                        {
                            AnimalId = 19,
                            AvailabilityStatus = true,
                            Description = "Affectionate and gentle Himalayan. Enjoys a calm and peaceful environment.",
                            IntakeDate = new DateTime(2023, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sophie",
                            Type = "Cat",
                            Weight = 6
                        },
                        new
                        {
                            AnimalId = 20,
                            AvailabilityStatus = true,
                            Description = "Energetic and friendly Australian Shepherd. Loves outdoor activities and playing fetch.",
                            IntakeDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bentley",
                            Type = "Dog",
                            Weight = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
